networks:
  smartbrain:

services:
  frontend:
    container_name: smartbrain_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ..:/workspaces:z,cached
    environment:
      DEVCONTAINER: true
      NODE_ENV: local
    command: sleep infinity
    networks:
      - smartbrain
    ports:
      - "3000:3000"
    working_dir: /workspaces/frontend
    depends_on:
      - backend
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  backend:
    container_name: smartbrain_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ..:/workspaces:z,cached
    command: sleep infinity
    environment:
      DEVCONTAINER: true
      NODE_ENV: local
    networks:
      - smartbrain
    ports:
      - "3001:3001"
    working_dir: /workspaces/backend
    depends_on:
      - backend-db

  backend-db:
    container_name: smartbrain_db
    build:
      context: .
      dockerfile: database/Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - smartbrain
    ports:
      - "5432:5432"

volumes:
  postgres-data:
