networks:
  smartbrain:

services:
  frontend:
    container_name: smartbrain_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ..:/workspaces:z,cached
    environment:
      DEVCONTAINER: true
      NODE_ENV: development
    command: sleep infinity
    networks:
      - smartbrain
    expose:
      - 3000
    ports:
      - 3000
    working_dir: /workspaces/frontend
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  backend:
    container_name: smartbrain_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ..:/workspaces:z,cached
    command: sleep infinity
    environment:
      DEVCONTAINER: true
      NODE_ENV: development
      PORT: 3001
    networks:
      - smartbrain
    expose:
      - 3001
    working_dir: /workspaces/backend

  backend_db:
    container_name: smartbrain_db
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - smartbrain
    ports:
      - 5432

volumes:
  postgres-data:
