networks:
  smartbrain:

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:z,cached
    environment:
      DEVCONTAINER: true
    command: sleep infinity
    networks:
      - smartbrain
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:z,cached
    command: sleep infinity
    environment:
      DEVCONTAINER: true
    networks:
      - smartbrain

  backend_db:
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - smartbrain

volumes:
  postgres-data:
