name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    pull_requests:
      branches:
        - "main"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          configFile: .github/.devcontainer/base/devcontainer.json
          imageName: ghcr.io/${{ github.repository }}-base
          cacheFrom: ghcr.io/${{ github.repository }}-base
          runCmd: 'echo ''eval "$(starship init bash)"'' | sudo tee -a /etc/bash.bashrc'
          push: always
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          configFile: .github/.devcontainer/dind/devcontainer.json
          imageName: ghcr.io/${{ github.repository }}-dind
          cacheFrom: ghcr.io/${{ github.repository }}-dind
          push: always
